### ISSUE TITLE
animations in 2D don't work

### ISSUE THREAD

**Issue by francescovigot** [yasirkula/UnitySimpleInput#1]
hello thank u for your amazing plugin
there are 2 problems for me , why the animations in 2D (for example walking,Running) don't work?
when i use keyboard ,player walks as its animation set , but when i use joystick walk animation just slides not walk
and the second problem is when i click on screen for first time to pull joystick to right or left fire1 performs

I used this tutorial
[https://www.youtube.com/watch?v=3BLGBrTpqh4](url)
 ```
   void walking() {
    
        if (!isDead)
        {
            dirx = SimpleInput.GetAxisRaw("Horizontal") * walkspeed;
        }
        if (dirx == 0)
        {
            anim.SetBool("isWalking", false);
            anim.SetBool("isRunning", false);
        }
if (Mathf.Abs(dirx) == 5 && rg.velocity.y == 0)
        {
            anim.SetBool("isWalking", true);
        }
   
    }

```

**Comment by yasirkula** [comment]
Please see this post: https://forum.unity.com/threads/simple-input-use-custom-input-providers-like-joysticks-ui-buttons-and-d-pads-open-source.520504/#post-3746737
