### ISSUE TITLE
Line of code giving me errors + FIX

### ISSUE THREAD

**Issue by Br1lopez** [yasirkula/UnitySimpleInput#2]
Hello and thank you for your plugin.

It has been very useful for me, but I recently had a little problem with it.

Each time I loaded a new Scene through code, the same error message kept appearing to me (_ArgumentOutOfRangeException: Argument is out of range. Parameter name: index_).

Apparently, the origin of this issue is the following line of code (line 178) in _SimpleInput.cs_:

      for( int i = 0; i < trackedTemporaryButtons.Count; i++ )
			trackedTemporaryMouseButtons[i].StopTracking();

I changed it like this and the error seems to dissapear:

      for( int i = 0; i < trackedTemporaryMouseButtons.Count; i++ )
			trackedTemporaryMouseButtons[i].StopTracking();

I think it is just a small error, but I felt the need to share it with you.

Thank you very much,

Bruno.

**Comment by yasirkula** [comment]
You are right! That for-loop was apparently a copy&paste victim. Fixed the issue in https://github.com/yasirkula/UnitySimpleInput/commit/aee2642aadc3938b604c5bdb8e00541a1fb9b51b
