### ISSUE TITLE
DPad detects touch in the corners between the arrows

### ISSUE THREAD

**Issue by jcarellanov** [yasirkula/UnitySimpleInput#3]
Hi, I'm using the DPad on Unity 2019.2.4f1. I've set up the dpad to move my character. This works well. I know I'm trying to let the users know whenever their fingers are touching one of the four arrows on the dpad (so that they wont have to look away from the screen). 

I've put my code in dpad.cs inside CalculateInput(), and touching the arrows is detected. However, touching the empty spaces between the arrows (the corners of the dpad "square") also triggers my code. Touching the center of the dpad does not (as intended).

**Comment by yasirkula** [comment]
When the finger is on the corners, both m_value.x and m_value.y should be different from 0 at the end of the CalculateInput function. You should execute your code only if `( m_value.x != 0 ) != ( m_value.y != 0 )`.

**Comment by jcarellanov** [comment]
This works, thanks! Closing the issue now.
