### ISSUE TITLE
Input Button UI that passes input through to elements under it?

### ISSUE THREAD

**Issue by Ichicoro** [yasirkula/UnitySimpleInput#4]
Hello. I currently have a Canvas with two Panels (one is a "Joystick", and the other one is a "Touchpad" that controls the Touch X and Touch Y axis, which control the camera). I would like to have the option to let the "Input Button UI" component pass its touch/pointer data to the component below, to make it possible to tap on the button then drag your finger to move the camera. Is there any way to do so?

I can't find anything :(

**Comment by yasirkula** [comment]
I believe the easiest solution would be to copy the Touchpad component to the "Input Button UI" object.

**Comment by Ichicoro** [comment]
Sorry for responding late. I tried extending Touchpad and adding code to check on pointer down/up and it worked. Thanks for the suggestion! :)
